name: Release

on:
  release:
    types: [published]

env:
  PLUGIN_NAME: obsidian-kindle-plugin

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"

      - name: Update package.json version
        uses: jossef/action-set-json-field@v2
        with:
          file: package.json
          field: version
          value: ${{ github.ref_name }}

      - name: Update manifest.json version
        uses: jossef/action-set-json-field@v2
        with:
          file: manifest.json
          field: version
          value: ${{ github.ref_name }}

      - name: Validate and open PR
        uses: guardian/actions-merge-release-changes-to-protected-branch@v1.0.0
        with:
            github-token: ${{ secrets.GU_GITHUB_TOKEN }}

      - name: Build
        id: build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          npm install
          npm run lint
          npm run test
          npm run build
          zip -r -j ${{ env.PLUGIN_NAME }}.zip dist -x "*.map"
          ls
          echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"

      - name: Upload main.js
        id: upload-main
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/main.js
          asset_name: main.js
          asset_content_type: text/javascript

      - name: Upload manifest.json
        id: upload-manifest
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/manifest.json
          asset_name: manifest.json
          asset_content_type: application/json

      - name: Upload plugin zip package
        id: upload-zip-package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.PLUGIN_NAME }}.zip
          asset_name: ${{ env.PLUGIN_NAME }}-${{ steps.build.outputs.tag_name }}.zip
          asset_content_type: application/zip
